# Generated by Django 5.0.4 on 2024-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_tasks', models.IntegerField()),
                ('all_tasks_in_work', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
