# Generated by Django 5.0.4 on 2024-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0004_delete_tasksinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_tasks', models.IntegerField(default=0)),
                ('all_tasks_in_work', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
