# Generated by Django 5.0.4 on 2024-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0005_alltasks_alter_task_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_tasks', models.IntegerField(default=0)),
                ('closed_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AllTasks',
        ),
    ]
