# Generated by Django 5.0.4 on 2024-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_taskstats_delete_alltasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstats',
            name='poused_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
